grid:
    dto: App\DTOs\CufpaTaxe
    entity: App\Entity\CufpaTaxe
    columns:
        id:
            title: Id
            field: c0_.id
            hidden: true
        activite:
            title: Activité
            field: c0_.activite
        opco:
            title: Opco
            field: c0_.opco
        taxeType:
            title: Taxe Type
            field: c0_.taxeType
            default: true
        isMasseSalarialeTotale:
            title: has MasseSalariale Totale
            field: c0_.isMasseSalarialeTotale
            default: true
        isMasseSalarialeCdd:
            title: has MasseSalariale Cdd
            field: c0_.isMasseSalarialeCdd
            default: true
        isMasseSalarialeIntermittent:
            title: has MasseSalariale Int
            field: c0_.isMasseSalarialeIntermittent
            default: true
        effectifMin:
            title: Effectif min
            field: c0_.effectifMin
            default: true
        effectifMax:
            title: Effectif max
            field: c0_.effectifMax
            default: true
        libelle:
            title: has MasseSalariale Int
            field: c0_.libelle
            default: true
        montantValeur:
            title: Montant
            field: c0_.montantValeur
            default: true
        montantOperation:
            title: Montant operation
            field: c0_.montantOperation
            default: true
        minimumApplicableValeur:
            title: min applicable valeur
            field: c0_.minimumApplicableValeur
            default: true
        minimumApplicableOperation:
            title: min applicable operation
            field: c0_.minimumApplicableOperation
            default: true
    filters:
        isMasseSalarialeTotale:
            title: Masse salariale totale
            type: select
            options:
                1: oui
                0: non
        montantOperation:
            title: Montant operation
            type: select
            options:
                euro: Euro
                pourcent: Pourcentage